### ISSUE TITLE
Bug when running example code

### ISSUE THREAD

**Issue by vaalwan** [zestai/zrp#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened! 

Hi! I am a PhD student working on a project and would want to use the zrp package for it. I am following your example code in ZRP-Tutorial.ipynb and can't figure out why I keep getting the following bug. Specifically, when I run 'zrp_output = zest_race_predictor.transform(zrp_sample)' I keep getting the following error:

'No such file or directory: '/home/valwan/.local/lib/python3.8/site-packages/zrp/prepare/../data/processed/geo/2019/Zest_Geo_Lookup_2019_State_34.parquet'

Is there something I need to update or change with the zrp package? Please let me know!

Thanks!
Vanessa Alwan

### Environment

```markdown
- OS:
- Node:
- yarn:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by kasey-zest** [comment]
Hi, thanks for reporting this! Did you download the support files using: `python -m zrp download` after pip installing ZRP?

**Comment by chriswill21** [comment]
@vaalwan could you please share this new stack trace error?
